name: Go

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Build
        run: go build -v -o ./output/imgfeedtovideo ./...

      - name: Build WIN
        run: GOOS=windows GOARCH=amd64 go build -v -o ./output/imgfeedtovideo.exe ./...

      - name: Collect builds
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: output/*
